//! Conversions shared by the two generation paths.
//!
//! Solidity tests reach the generator either by calling `hegel.draw*` directly or
//! by declaring ABI arguments the runner fills in. Both paths must render and
//! constrain values identically, or the same counterexample prints differently
//! depending on how it was produced.

use alloy_dyn_abi::DynSolValue;
use alloy_primitives::{I256, U256, hex};

/// Largest value an `address` can hold.
pub fn address_max() -> U256 {
    (U256::from(1) << 160) - U256::from(1)
}

/// Map arbitrary generated bytes onto printable ASCII.
///
/// Solidity strings are unconstrained byte arrays, so the engine's raw output is
/// a legal `string`. It is not, however, a legal *counterexample*: a reproduce
/// blob is only useful if the value it prints can be pasted back into a test, and
/// arbitrary bytes render as replacement characters. Restricting generation to
/// printable ASCII keeps reported strings faithful.
pub fn printable_string(bytes: Vec<u8>) -> String {
    bytes
        .into_iter()
        .map(|byte| char::from(32 + byte % 95))
        .collect()
}

/// Approximate a signed 256-bit score as the `f64` the engine's targeting API
/// takes. Scores beyond `f64` precision saturate, which only coarsens the search
/// gradient.
pub fn i256_as_f64(value: I256) -> f64 {
    match i128::try_from(value) {
        Ok(value) => value as f64,
        Err(_) if value.is_negative() => f64::MIN,
        Err(_) => f64::MAX,
    }
}

/// Render a value the way a Solidity literal would read, for counterexamples.
pub fn format_value(value: &DynSolValue) -> String {
    match value {
        DynSolValue::Bool(value) => value.to_string(),
        DynSolValue::Int(value, _) => value.to_string(),
        DynSolValue::Uint(value, _) => value.to_string(),
        DynSolValue::FixedBytes(value, size) => format!("0x{}", hex::encode(&value[..*size])),
        DynSolValue::Address(value) => value.to_string(),
        DynSolValue::Function(value) => format!("0x{}", hex::encode(value)),
        DynSolValue::Bytes(value) => format!("hex\"{}\"", hex::encode(value)),
        DynSolValue::String(value) => format!("{value:?}"),
        DynSolValue::Array(values) | DynSolValue::FixedArray(values) => {
            format!("[{}]", join(values))
        }
        DynSolValue::Tuple(values) => format!("({})", join(values)),
    }
}

fn join(values: &[DynSolValue]) -> String {
    values
        .iter()
        .map(format_value)
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_strings_survive_a_round_trip_through_the_report() {
        // Every byte the engine can emit must land in the printable range, or a
        // reported counterexample stops being copy-pasteable Solidity.
        let text = printable_string((0..=255).collect());
        assert!(text.chars().all(|c| (' '..='~').contains(&c)));
        assert_eq!(text.chars().count(), 256);
    }

    #[test]
    fn oversized_target_scores_saturate_instead_of_wrapping() {
        assert_eq!(i256_as_f64(I256::ZERO), 0.0);
        assert_eq!(i256_as_f64(I256::MINUS_ONE), -1.0);
        assert_eq!(i256_as_f64(I256::MAX), f64::MAX);
        assert_eq!(i256_as_f64(I256::MIN), f64::MIN);
    }
}
